Update as primitive
vtex/react-upload-csv pull request #5
Opened 2017-09-18 15:00 UTC by kevinch

#### What is the purpose of this pull request?
Update package as a primitive.

#### What problem is this solving?

#### Screenshots or example usage

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2017-09-18 15:26 UTC, kevinch commented
Linked to https://github.com/vtex/react-csv-parse/issues/2

2017-09-18 16:49 UTC, klzns requested changes

2017-09-18 16:49 UTC, brenoc commented on demo/src/index.js
> +        <input type="file" onChange={this.handleFileInputChange} />
Acho que faz mais sentido isso ta dentro do `children` do componente.

Ex:
```js

class Demo extends Component {
	state = {
		data: null
	}

	handleParsedData = (data) => {
		this.setState({ data })
	}

	render() {
		const { data } = this.state

		// aqui o mesmo codigo de fileHeaders e tableColumns

		if (!data) {
            // Como ainda não tem dados, renderiza o input de upload
            // com o CsvParse ao redor para tratar o seu arquivo
			return (
				<CsvParse
					fileHeaders={fileHeaders}
					onParsedData={this.handleParsedData}>
					{onChange =>
						<input type="file" onChange={this.onChange} />
					}
				</CsvParse>
			)
		}

		return (
			<div>
				<p><strong>Raw Data:</strong></p>
				<SyntaxHighlighter
					language="json"
					style={docco}
					showLineNumbers
				>
					{JSON.stringify(data)}
				</SyntaxHighlighter>

				<p><strong>Data in table:</strong></p>
				<ReactTable
					data={data}
					defaultPageSize={10}
					columns={tableColumns}
				/>
			</div>
		)
	}
}
```

2017-09-18 16:49 UTC, brenoc commented on demo/src/index.js
> +        <CsvParse file={this.state.file} apiKeys={fileHeaders}>
O nome `apiKeys` é meio distante de arquivo csv.

2017-09-18 16:49 UTC, brenoc commented on demo/src/index.js
> +        <CsvParse file={this.state.file} apiKeys={fileHeaders}>
Eu gostei do nome da variavel `fileHeaders` seria uma prop legal

2017-09-18 16:49 UTC, brenoc commented on src/index.js
> +} from "ramda"
O ramda deve ta dando um peso tenso no componente. Se conseguir não usar ele ou usar o lodash que importa só as funçõs que de fato ta usando, acho que seria melhor.

Não sei se o plugin babel do ramda consegue tirar as funcoes que não tao sendo usadas.

Vale a pena checar isso.

2017-09-18 17:10 UTC, kevinch commented on src/index.js
> +} from "ramda"
Vou usar o plugin pro babel que pega apenas as funções em uso. Good catch.

2017-09-18 20:10 UTC, nandoacoelho commented on README.md
> +```
` ```js ` é melhor já que tem syntax highlight

2017-09-18 20:10 UTC, nandoacoelho commented on README.md
> +```
mesmo aqui

2017-09-18 20:10 UTC, nandoacoelho commented on demo/src/index.js
> +    const file = event.target.files[0]
aqui é de propósito pegar só o primeiro?

2017-09-18 20:37 UTC, kevinch commented on README.md
> +```
Good point.

2017-09-18 22:51 UTC, kevinch commented on demo/src/index.js
> +        <input type="file" onChange={this.handleFileInputChange} />
Atualizado.

2017-09-19 13:24 UTC, nandoacoelho commented on src/index.js
> +  handleOnChange = event => {
não seria melhor assim direto?

```js
handleOnChange = event => this.formatFileResult(event.target.files[0], this.props.fileHeaders)
```

2017-09-19 13:53 UTC, klzns approved these changes

2017-09-19 13:55 UTC, kevinch commented on src/index.js
> +  handleOnChange = event => {
Acho mais facil de ler:
```js
const file = event.target.files[0]
this.formatFileResult(file, this.props.fileHeaders)
```

2017-09-19 13:55 UTC, kevinch commented on src/index.js
> +  handleOnChange = event => {
eh, apples and oranges ne?

2017-09-19 13:56 UTC, nandoacoelho commented on src/index.js
> +  handleOnChange = event => {
tomato potato

2017-09-19 13:56 UTC, omninando approved these changes

2017-09-19 16:51 UTC, merged